In [1]:
import cv2
import numpy as np
#MUH.CHOLISH SAID_202331076

In [2]:
citra = cv2.imread('buah.jpg')  
#MUH.CHOLISH SAID_202331076

In [3]:
cv2.imshow("citra asli", citra)
cv2.waitKey(10000)
cv2.destroyAllWindows()
#MUH.CHOLISH SAID_202331076

In [4]:
print(citra.shape)
print(citra.dtype)
#MUH.CHOLISH SAID_202331076

(416, 612, 3)
uint8


In [5]:
b = citra [:,:,0]
g = citra [:,:,1]
r = citra [:,:,2]
#MUH.CHOLISH SAID_202331076

In [7]:
panjang = len(citra) #menghitung baris
lebar = len (citra[0]) #menghitung kolom

citra_gray = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar) :
        citra_gray[i,j] = 0.2989 * r[i,j] + 0.587 * g[i,j] + 0.1141 *b[i,j] 
        #merah = 29,89% ; hijau = 58,7% ; biru 11,41%

citra_gray = citra_gray.astype(np.uint8)

cv2.imshow("citra grayscale", citra_gray)
cv2.waitKey()
cv2.destroyAllWindows()
#MUH.CHOLISH SAID_202331076

In [8]:
print (citra)
#MUH.CHOLISH SAID_202331076

[[[ 96 224 255]
  [ 78 231 252]
  [140 224 250]
  ...
  [152 161 205]
  [117 148 187]
  [ 72 122 158]]

 [[ 54 217 250]
  [ 56 227 249]
  [137 223 253]
  ...
  [ 45  63  94]
  [ 33  42  75]
  [ 21  24  55]]

 [[ 22 214 251]
  [ 38 226 254]
  [127 227 255]
  ...
  [ 29  72  89]
  [ 42  55  77]
  [ 57  47  70]]

 ...

 [[  1 130 255]
  [  3 132 255]
  [  4 133 255]
  ...
  [ 36 172 254]
  [ 26 168 251]
  [ 15 165 249]]

 [[  0 129 254]
  [  2 131 255]
  [  3 132 255]
  ...
  [ 22 172 255]
  [ 14 169 254]
  [  8 167 254]]

 [[  0 128 253]
  [  0 129 254]
  [  1 130 255]
  ...
  [  7 171 254]
  [  6 171 255]
  [  7 172 255]]]


In [9]:
print (citra_gray)
#MUH.CHOLISH SAID_202331076

[[218 219 222 ... 173 156 127]
 [208 214 222 ...  70  50  32]
 [203 212 223 ...  72  60  55]
 ...
 [152 154 154 ... 180 176 172]
 [151 153 154 ... 179 176 174]
 [150 151 152 ... 177 177 177]]


In [10]:
panjang = len(citra) #menghitung baris
lebar = len (citra[0]) #menghitung kolom

ambang = 90

citra_biner = np.zeros((panjang,lebar))
for i in range (panjang):
    for j in range (lebar) :
        if citra_gray[i,j]>= ambang:
            citra_biner[i,j] = 1 #putih
        else:
            citra_biner[i,j] = 0 #putih
cv2.imshow("citra binary", citra_biner)
cv2.waitKey()
cv2.destroyAllWindows()
#MUH.CHOLISH SAID_202331076

In [11]:
print (citra_biner)
#MUH.CHOLISH SAID_202331076

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
